# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install build dependencies for psutil and other native extensions
RUN apt-get update && apt-get install -y gcc python3-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY requirements.txt ./
COPY pyproject.toml ./
COPY README.md ./
COPY mcp_server.py ./
COPY gdb_tools.py ./
COPY comm_methods ./comm_methods

# Install python dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "mcp_server.py"]
